package promo

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/ssankrith/kart-backend/internal/domain"
)

func LoadPromo(couponDataDir string) (domain.PromoChecker, error) {
	// Prefer precomputed FNV shard files generated by cmd/preprocessor_seq.
	// Users can set PROMO_SHARDS_DIR; otherwise we try a couple of common locations.
	candidates := []string{}
	if v := os.Getenv("PROMO_SHARDS_DIR"); v != "" {
		candidates = append(candidates, v)
	}
	// Relative to the current working directory (useful for local `go run` from repo root).
	candidates = append(candidates, "./shards_seq")
	// Under the coupon data directory (useful for Docker / deployments).
	candidates = append(candidates, filepath.Join(couponDataDir, "shards_seq"))

	for _, dir := range candidates {
		if dir == "" {
			continue
		}
		if HasShardsIndex(dir) {
			log.Printf("promo: loading shards index from %s", dir)
			if err := maybeValidateManifest(dir); err != nil {
				return nil, err
			}
			return LoadShardsPromo(dir)
		}
	}
	return nil, fmt.Errorf("promo: no shards index found (tried: %v). Generate shards with cmd/preprocessor_seq and set PROMO_SHARDS_DIR", candidates)
}

func maybeValidateManifest(dir string) error {
	strict := strings.TrimSpace(os.Getenv("PROMO_SHARDS_STRICT")) == "1"
	m, err := ReadManifest(dir)
	if err != nil {
		return fmt.Errorf("promo manifest: %w", err)
	}
	if m == nil {
		if strict {
			return fmt.Errorf("promo: %s missing under %s (set PROMO_SHARDS_STRICT=0 to allow)", ManifestFileName, dir)
		}
		log.Printf("promo: %s not found under %s (skipping integrity check)", ManifestFileName, dir)
		return nil
	}
	if err := ValidateManifest(dir, m); err != nil {
		if strict {
			return fmt.Errorf("promo manifest validation: %w", err)
		}
		log.Printf("promo: manifest validation warning: %v", err)
	}
	return nil
}

// HasShardsIndex checks whether a shards directory looks usable.
// We only require the presence/shape of a small set of shard files because
// ShardsChecker loads shards lazily on demand.
func HasShardsIndex(dir string) bool {
	// Must include at least shard 000.bin with valid record sizing.
	p := filepath.Join(dir, "000.bin")
	st, err := os.Stat(p)
	if err != nil || st.Size()%shardEntrySize != 0 {
		return false
	}
	return true
}
